packages:
  - apps/*
  - envs/**
  - packages/**
publicHoistPattern:
  - '*@srcube-taro/*'
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@babel/core': ^7.24.4
  '@babel/plugin-proposal-class-properties': 7.14.5
  '@babel/plugin-transform-optional-chaining': ^7.27.1
  '@babel/preset-react': ^7.24.1
  '@babel/runtime': ^7.24.4
  '@changesets/cli': ^2.29.4
  '@egoist/tailwindcss-icons': ^1.9.0
  '@eslint-react/eslint-plugin': ^1.49.0
  '@eslint/eslintrc': ^3
  '@heroui/react': ^2.7.0
  '@iconify/json': ^2.2.329
  '@mdx-js/loader': ^3.1.0
  '@mdx-js/mdx': ^3.1.0
  '@next/mdx': ^15.2.4
  '@pmmmwh/react-refresh-webpack-plugin': ^0.5.5
  '@stefanprobst/rehype-extract-toc': ^2.2.1
  '@tailwindcss/postcss': ^4
  '@tailwindcss/typography': ^0.5.16
  '@tarojs/cli': 4.0.9
  '@tarojs/components': 4.0.9
  '@tarojs/helper': 4.0.9
  '@tarojs/plugin-framework-react': 4.0.9
  '@tarojs/plugin-platform-alipay': 4.0.9
  '@tarojs/plugin-platform-h5': 4.0.9
  '@tarojs/plugin-platform-harmony-hybrid': 4.0.9
  '@tarojs/plugin-platform-jd': 4.0.9
  '@tarojs/plugin-platform-qq': 4.0.9
  '@tarojs/plugin-platform-swan': 4.0.9
  '@tarojs/plugin-platform-tt': 4.0.9
  '@tarojs/plugin-platform-weapp': 4.0.9
  '@tarojs/react': 4.0.9
  '@tarojs/runtime': 4.0.9
  '@tarojs/shared': 4.0.9
  '@tarojs/taro': 4.0.9
  '@tarojs/taro-loader': 4.0.9
  '@tarojs/webpack5-runner': 4.0.9
  '@types/lodash-es': ^4.17.12
  '@types/mdx': ^2.0.13
  '@types/node': ^18
  '@types/react': ^18.0.0
  '@types/react-dom': ^18
  '@types/underscore': ^1.13.0
  '@types/webpack-env': ^1.13.6
  autoprefixer: ^10.4.21
  babel-preset-taro: 4.0.9
  classnames: ^2.5.1
  clean-publish: ^5.1.0
  dayjs: ^1.11.13
  eslint: ^9.23.0
  eslint-config-next: ^15.2.4
  eslint-config-taro: 4.0.9
  eslint-plugin-react: ^7.34.1
  eslint-plugin-react-hooks: ^4.4.0
  eslint-plugin-react-refresh: ^0.4.20
  globals: ^16.0.0
  hast-util-to-jsx-runtime: ^2.3.6
  lodash-es: ^4.17.21
  mdx: ^0.3.1
  nanoid: ^5.1.5
  next: ^15.2.4
  next-themes: ^0.4.6
  postcss: ^8.4.38
  react: ^18
  react-dom: ^18
  react-error-boundary: ^6.0.0
  react-is: ^18
  react-refresh: ^0.14.0
  rehype-slug: ^6.0.0
  remark-extract-frontmatter: ^3.2.0
  remark-frontmatter: ^5.0.0
  shiki: ^3.2.1
  stylelint: ^16.4.0
  tailwind-variants: ^1.0.0
  tailwindcss: ^3
  tailwindcss-animated: ^2.0.0
  tarojs-router-next: ^3.4.6
  tarojs-router-next-plugin: ^3.4.6
  tsconfig-paths-webpack-plugin: ^4.1.0
  tsup: ^8.4.0
  typescript: ^5.8.3
  weapp-tailwindcss: ^3
  webpack: 5.91.0
  yaml: ^2.7.1
